version: '2.1'

services:
  cybercolecatchingsystem:
    image: cybercolecatchingsystem
    #build: .
    ports:
      - 3000:3000
  chrome:
    image: elgalu/selenium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:24444
